# Generated by Django 4.1.2 on 2022-10-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectname',
            name='obj_type',
            field=models.IntegerField(choices=[(0, 'Even'), (1, 'Odd'), (2, 'Weekly')], default=2),
        ),
        migrations.AddField(
            model_name='objectname',
            name='peer_number',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectname',
            name='week_day',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectname',
            name='grup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.grup'),
        ),
        migrations.AlterField(
            model_name='objectname',
            name='prof',
            field=models.ManyToManyField(null=True, to='users.prof'),
        ),
        migrations.AlterField(
            model_name='objectname',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.room'),
        ),
    ]
