# Generated by Django 4.1.3 on 2022-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lesson_rename_grup_group_delete_objectname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='prof',
            field=models.ManyToManyField(to='users.prof'),
        ),
    ]
